/**
 * SchoolsPedia — Hindi translation dictionary and helpers
 * Maps states, districts, categories, and static UI texts.
 */

const TRANSLATIONS = {
  // States
  'uttar-pradesh': 'उत्तर प्रदेश',
  'bihar': 'बिहार',
  'madhya-pradesh': 'मध्य प्रदेश',

  // UP Districts
  'lucknow': 'लखनऊ',
  'kanpur-nagar': 'कानपुर नगर',
  'kanpur-dehat': 'कानपुर देहात',
  'varanasi': 'वाराणसी',
  'prayagraj': 'प्रयागराज',
  'agra': 'आगरा',
  'meerut': 'मेरठ',
  'ghaziabad': 'गाजियाबाद',
  'bareilly': 'बरेली',
  'aligarh': 'अलीगढ़',
  'gorakhpur': 'गोरखपुर',
  'moradabad': 'मुरादाबाद',
  'jhansi': 'झाँसी',
  'saharanpur': 'सहारनपुर',
  'ayodhya': 'अयोध्या',
  'muzaffarnagar': 'मुजफ्फरनगर',
  'mathura': 'मथुरा',
  'budaun': 'बदायूँ',
  'shahjahanpur': 'शाहजहाँपुर',
  'pilibhit': 'पीलीभीत',
  'sitapur': 'सीतापुर',
  'hardoi': 'हरदोई',
  'unnao': 'उन्नाव',
  'rae-bareli': 'रायबरेली',
  'kheri': 'लखीमपुर खीरी',
  'barabanki': 'बाराबंकी',
  'sultanpur': 'सुल्तानपुर',
  'amethi': 'अमेठी',
  'bahraich': 'बहराइच',
  'shrawasti': 'श्रावस्ती',
  'balrampur': 'बलरामपुर',
  'gonda': 'गोण्डा',
  'siddharthnagar': 'सिद्धार्थनगर',
  'basti': 'बस्ती',
  'sant-kabir-nagar': 'संत कबीर नगर',
  'maharajganj': 'महराजगंज',
  'kushinagar': 'कुशीनगर',
  'deoria': 'देवरिया',
  'azamgarh': 'आजमगढ़',
  'mau': 'मऊ',
  'ballia': 'बलिया',
  'jaunpur': 'जौनपुर',
  'ghazipur': 'गाजीपुर',
  'chandauli': 'चंदौली',
  'mirzapur': 'मिर्जापुर',
  'sonbhadra': 'सोनभद्र',
  'bhadohi': 'भदोही',
  'etawah': 'इटावा',
  'auraiya': 'औरैया',
  'farrukhabad': 'फर्रुखाबाद',
  'kannauj': 'कन्नौज',
  'mainpuri': 'मैनपुरी',
  'firozabad': 'फिरोजाबाद',
  'kanshiram-nagar': 'कासगंज',
  'etah': 'एटा',
  'hathras': 'हाथरस',
  'bulandshahr': 'बुलंदशहर',
  'hapur-panchsheel-nagar': 'हापुड़',
  'bagpat': 'बागपत',
  'bijnor': 'बिजनौर',
  'jyotiba-phule-nagar-amroha': 'अमरोहा',
  'sambhal-bhim-nagar': 'संभल',
  'rampur': 'रामपुर',
  'shamli-prabudh-nagar': 'शामली',
  'banda': 'बांदा',
  'chitrakoot': 'चित्रकूट',
  'hamirpur': 'हमीरपुर',
  'mahoba': 'महोबा',
  'jalaun': 'जालौन',
  'lalitpur': 'ललितपुर',
  'kaushambi': 'कौशाम्बी',
  'fatehpur': 'फतेहपुर',
  'pratapgarh': 'प्रतापगढ़',
  'gautam-buddha-nagar': 'गौतम बुद्ध नगर',
  'ahraura': 'अहरौरा',
  'amroha': 'अमरोहा',
  'hapur': 'हापुड़',
  'kasganj': 'कासगंज',
  'sambhal': 'संभल',
  'shamli': 'शामली',
  
  // Bihar Districts
  'araria': 'अररिया',
  'arwal': 'अरवल',
  'aurangabad-bihar': 'औरंगाबाद',
  'banka': 'बांका',
  'begusarai': 'बेगूसराय',
  'bhagalpur': 'भागलपुर',
  'bhojpur': 'भोजपुर',
  'buxar': 'बक्सर',
  'darbhanga': 'दरभंगा',
  'gaya': 'गया',
  'gopalganj': 'गोपालगंज',
  'jamui': 'जमुई',
  'jehanabad': 'जहानाबाद',
  'kaimur-bhabua': 'कैमूर (भभुआ)',
  'katihar': 'कटिहार',
  'khagaria': 'खगड़िया',
  'kishanganj': 'किशनगंज',
  'lakhisarai': 'लखीसराय',
  'madhepura': 'मधेपुरा',
  'madhubani': 'मधुबनी',
  'munger': 'मुंगेर',
  'muzaffarpur': 'मुजफ्फरपुर',
  'nalanda': 'नालंदा',
  'nawada': 'नवादा',
  'pashchim-champaran': 'पश्चिम चंपारण',
  'patna': 'पटना',
  'purba-champaran': 'पूर्वी चंपारण',
  'purnia': 'पूर्णिया',
  'rohtas': 'रोहतास',
  'saharsa': 'सहरसा',
  'samastipur': 'समस्तीपुर',
  'saran': 'सारण',
  'sheikhpura': 'शेखपुरा',
  'sheohar': 'शिवहर',
  'sitamarhi': 'सीतामढ़ी',
  'siwan': 'सीवान',
  'supaul': 'सुपौल',
  'vaishali': 'वैशाली',

  // MP Districts
  'agar-malwa': 'आगर मालवा',
  'alirajpur': 'अलीराजपुर',
  'anuppur': 'अनूपपुर',
  'ashoknagar': 'अशोकनगर',
  'balaghat': 'बालाघाट',
  'barwani': 'बड़वानी',
  'betul': 'बैतुल',
  'bhind': 'भिंड',
  'bhopal': 'भोपाल',
  'burhanpur': 'बुरहानpur',
  'chhatarpur': 'छतरपुर',
  'chhindwara': 'छिंदवाड़ा',
  'damoh': 'दमोह',
  'datia': 'दतिया',
  'dewas': 'देवास',
  'dhar': 'धार',
  'dindori': 'डिंडोरी',
  'guna': 'गुना',
  'gwalior': 'ग्वालियर',
  'harda': 'हरदा',
  'hoshangabad': 'होशंगाबाद',
  'indore': 'इन्दौर',
  'jabalpur': 'जबलपुर',
  'jhabua': 'झाबुआ',
  'katni': 'कटनी',
  'khandwa': 'खंडवा',
  'khargone': 'खरगोन',
  'mandla': 'मंडला',
  'mandsaur': 'मंदसौर',
  'morena': 'मुरैना',
  'narsimhapur': 'नरसिंहपुर',
  'neemuch': 'नीमच',
  'niwari': 'निवाड़ी',
  'panna': 'पन्ना',
  'raisen': 'रायसेन',
  'rajgarh': 'राजगढ़',
  'ratlam': 'रतलाम',
  'rewa': 'रीवा',
  'sagar': 'सागर',
  'satna': 'सतना',
  'sehore': 'सीहोर',
  'seoni': 'सिवनी',
  'shahdol': 'शहडोल',
  'shajapur': 'शाजापुर',
  'sheopur': 'श्योपुर',
  'shivpuri': 'शिवपुरी',
  'sidhi': 'सीधी',
  'singrauli': 'सिंगरौली',
  'tikamgarh': 'टीकमगढ़',
  'ujjain': 'उज्जैन',
  'umaria': 'उमरिया',
  'vidisha': 'विदिशा',

  // Categories
  'Primary': 'प्राथमिक',
  'Upper Primary': 'उच्च प्राथमिक',
  'Secondary': 'माध्यमिक',
  'Higher Secondary': 'उच्चतर माध्यमिक',
  'Co-educational': 'सह-शिक्षा (Co-ed)',
  'Boys': 'बालक (Boys)',
  'Girls': 'बालिका (Girls)',

  // Managements
  'Department of Education': 'शिक्षा विभाग',
  'Private Unaided': 'निजी गैर-सहायता प्राप्त',
  'Private Aided': 'निजी सहायता प्राप्त',
  'Local Body': 'स्थानीय निकाय',
  'Government Aided': 'सरकारी सहायता प्राप्त',

  // UI Terms
  'Home': 'होम',
  'Schools': 'स्कूल',
  'Total Schools': 'कुल स्कूल',
  'Districts': 'जिले',
  'Blocks': 'ब्लॉक',
  'Villages': 'गाँव',
  'Schools in': 'में स्कूल',
  'Districts in': 'में जिले',
  'School categories in': 'में स्कूल की श्रेणियाँ',
  'Management type': 'प्रबंधन का प्रकार',
  'Educational Board': 'शिक्षा बोर्ड',
  'Visit Board Website': 'बोर्ड की वेबसाइट पर जाएं',
  'Search schools': 'स्कूल खोजें',
  'Search': 'खोजें',
  'Search from 16.5 lakh+ schools': '16.5 लाख+ स्कूलों में खोजें',
  'Search schools in': 'में स्कूल खोजें',
  'Filter schools by category': 'श्रेणी के अनुसार स्कूल फ़िल्टर करें',
  'View block': 'ब्लॉक देखें',
  'schools': 'स्कूल',
  'villages': 'गाँव',
  'Featured Schools in': 'में प्रमुख स्कूल',
  'Explore': 'देखें',
  'About': 'के बारे में',
  'FAQs': 'अक्सर पूछे जाने वाले प्रश्न',
  'Browse Nearby Districts in': 'में आस-पास के जिले देखें',
  'Census Data': 'जनगणना डेटा',
  'Literacy Rate': 'साक्षरता दर',
  'Population': 'जनसंख्या',
  'Sex Ratio': 'लिंगानुपात',
  'Operational': 'सक्रिय',
  'Closed': 'बंद'
};

export function t(key, lang = 'en') {
  if (lang === 'hi' && TRANSLATIONS[key]) {
    return TRANSLATIONS[key];
  }
  return key;
}

export function translateGeographicName(slug, englishName, lang = 'en') {
  if (lang === 'hi' && TRANSLATIONS[slug]) {
    return TRANSLATIONS[slug];
  }
  return englishName;
}
